accuracy: 0.9832000136375427
architecture: hidden:768|out:10--recur:128
architecture_name: s2_network
batch: 50
column_at_a_time: 7
dataset: mnist
dims: 28
epoch: 200
experiment_name: s2_network-mnist-seq-4---2018-01-28--15-42-21
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 4
val_accuracy: 0.9816666841506958
