accuracy: 0.9014999866485596
architecture: hidden:256|out:10--recur:256
architecture_name: shallow
batch: 50
column_at_a_time: 7
dataset: fashion-mnist-3-items-maj
dims: 28
epoch: 200
experiment_name: shallow-fashion-mnist-3-items-maj-seq-12---2018-02-27--00-25-48
keep_prob: 0.8
lr: 0.00025
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.9079166650772095
