accuracy: 0.6492999792098999
architecture: in1:256|hidden:512|out1:128|out2:10--recur:256
architecture_name: s3_network
batch: 50
column_at_a_time: 28
dataset: mnist
dims: 28
epoch: 50
experiment_name: s3-mnist-seq-1---2017-12-13--12-50-12
keep_prob: 0.5
lr: 0.0005
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 1
val_accuracy: 0.643833339214325
