accuracy: 0.9563000202178955
architecture: in1:100|hidden:100|out1:75|out2:10--recur:50
architecture_name: s3_network
batch: 100
column_at_a_time: 4
dims: 28
epoch: 2
experiment_name: rnn-2017-10-19--18-26
keep_prob: 0.8
lr: 0.0025
max_seq_length: 28
seq_length: 7
