accuracy: 0.9786999821662903
architecture: in1:512|hidden:256|out1:64|out2:10--recur:1
architecture_name: s3_network
batch: 50
column_at_a_time: 28
dataset: mnist
dims: 28
epoch: 200
experiment_name: s3_network-mnist-seq-1---2018-01-29--01-07-05
keep_prob: 0.5
lr: 0.0002
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 1
val_accuracy: 0.9784166812896729
