accuracy: 0.8937000036239624
architecture: in1:200|hidden:30|out1:20|out2:10--recur:20
architecture_name: s3_network
batch: 50
column_at_a_time: 7
dims: 28
epoch: 200
experiment_name: rnn-2017-11-03--10-32
keep_prob: 0.1
lr: 1.0e-05
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 4
