accuracy: 0.9800000190734863
architecture: hidden:256|out:10--recur:128
architecture_name: s2_network
batch: 50
column_at_a_time: 4
dataset: mnist
dims: 28
epoch: 50
experiment_name: s2-seq-7---2017-12-13--12-14-46
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 7
val_accuracy: 0.9736666679382324
