accuracy: 0.9840999841690063
architecture: in1:128|in2:256|hidden:128|out1:32|out2:10--recur:256
architecture_name: deep_v2
batch: 50
column_at_a_time: 4
dataset: mnist
dims: 28
epoch: 100
experiment_name: deep_v2-mnist-seq-7---2018-03-03--02-42-11
keep_prob: 0.8
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 7
val_accuracy: 0.9837499856948853
