accuracy: 0.9071000218391418
architecture: in1:128|in2:256|hidden:128|out1:32|out2:10--recur:256
architecture_name: deep_4l_network
batch: 50
column_at_a_time: 7
dataset: fashion-mnist-3-items-maj
dims: 28
epoch: 200
experiment_name: deep_4l_network-fashion-mnist-3-items-maj-seq-12---2018-02-21--01-16-19
keep_prob: 0.8
lr: 0.00025
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.9150000214576721
