accuracy: 0.9035999774932861
architecture: in1:512|in2:265|hidden:128|out1:64|out2:10--recur:128
architecture_name: deep_4l_network
batch: 50
column_at_a_time: 7
dataset: fashion-mnist-3-items-maj
dims: 28
epoch: 200
experiment_name: deep_4l_network-fashion-mnist-3-items-maj-seq-12---2018-02-18--02-11-56
keep_prob: 0.8
lr: 0.00025
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.909333348274231
