accuracy: 0.9937000274658203
architecture: conv1:5x5x48=>2x2[2,2]|conv2:3x3x56=>2x2[2,2]|hidden:256|out1:64|out2:10--recur:128
architecture_name: convdeep_4l_network
batch: 50
column_at_a_time: 28
dataset: mnist-7-digits
dims: 28
epoch: 200
experiment_name: convdeep_4l_network-mnist-7-digits-seq-7---2018-02-19--21-52-45
keep_prob: 0.8
lr: 0.0001
max_seq_length: 196
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 7
val_accuracy: 0.9917500019073486
