accuracy: 0.9944000244140625
architecture: conv1:5x5x24=>2x2[2,2]|conv2:3x3x48=>2x2[2,2]|hidden:256|out1:128|out2:10--recur:1
architecture_name: convdeep_4l_network
batch: 50
column_at_a_time: 28
dataset: mnist
dims: 28
epoch: 200
experiment_name: convdeep_4l_network-mnist-seq-1---2018-01-29--23-20-56
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 1
val_accuracy: 0.9931666851043701
