accuracy: 0.9941999912261963
architecture: conv1:5x5x16=>2x2[2,2]|conv2:5x5x32=>2x2[2,2]|hidden:512|out1:256|out2:10--recur:256
architecture_name: convdeep_4l_network
batch: 50
column_at_a_time: 28
dataset: mnist
dims: 28
epoch: 100
experiment_name: convdeep_4l_network-mnist-seq-1---2017-12-21--11-29-57
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 1
val_accuracy: 0.9929999709129333
