accuracy: 0.991100013256073
architecture: conv1:5x5x24=>2x2[2,2]|conv2:3x3x32=>2x2[2,2]|in1:128|hidden:128|out1:32|out2:10--recur:256
architecture_name: convdeep_4l_network
batch: 50
column_at_a_time: 28
dataset: mnist
dims: 28
epoch: 200
experiment_name: convdeep_4l_network-mnist-seq-1---2018-02-24--10-36-03
keep_prob: 0.8
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 1
val_accuracy: 0.9892500042915344
