accuracy: 0.9760000109672546
architecture: in1:100|hidden:100|out1:75|out2:10--recur:100
architecture_name: s3_network
batch: 100
column_at_a_time: 4
dims: 28
epoch: 50
experiment_name: rnn-2017-10-19--18-45
keep_prob: 1
lr: 0.0025
max_seq_length: 28
seq_length: 7
