accuracy: 0.9631999731063843
architecture: in1:300|hidden:100|out1:10|out2:10--recur:50
architecture_name: s3_network
batch: 50
column_at_a_time: 28
dims: 28
epoch: 50
experiment_name: rnn-2017-10-31--17-34
keep_prob: 0.4
lr: 0.005
max_seq_length: 28
seq_length: 1
