accuracy: 0.09799999743700027
architecture: hidden:60|out:10--recur:50
architecture_name: s2_network
batch: 50
column_at_a_time: 1
dims: 28
epoch: 50
experiment_name: s2-seq-28---2017-11-08--21-48-20
keep_prob: 1
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 28
val_accuracy: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - f4
  - 0
  - 1
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  FK7HPQ==
