accuracy: 0.9923999905586243
architecture: conv1:5x5x32=>2x2[2,2]|conv2:5x5x64=>2x2[2,2]|hidden:128|out1:64|out2:10--recur:1
architecture_name: tutorial_network
batch: 50
column_at_a_time: 28
dataset: mnist
dims: 28
epoch: 200
experiment_name: tutorial_network-mnist-seq-1---2018-02-03--21-54-20
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 1
val_accuracy: 0.9904166460037231
