accuracy: 0.9782000184059143
architecture: hidden:500|out:10--recur:250
architecture_name: s2_network
batch: 50
column_at_a_time: 28
dataset: mnist
dims: 28
epoch: 50
experiment_name: s2-seq-1---2017-12-13--11-40-51
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 1
val_accuracy: 0.9771666526794434
