accuracy: 0.8568999767303467
architecture: hidden:768|out:10--recur:128
architecture_name: s2_network
batch: 50
column_at_a_time: 7
dataset: fashion-mnist-3-items
dims: 28
epoch: 200
experiment_name: s2_network-fashion-mnist-3-items-seq-12---2018-02-07--23-33-47
keep_prob: 0.5
lr: 0.0001
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.8679999709129333
