accuracy: 0.8259999752044678
architecture: in1:500|hidden:1000|out1:500|out2:10--recur:375
architecture_name: s3_network
batch: 50
column_at_a_time: 28
dataset: fashion-mnist
dims: 28
epoch: 50
experiment_name: s3-fashion-mnist-seq-1---2017-12-10--21-33-48
keep_prob: 0.5
lr: 5.0e-05
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 1
val_accuracy: 0.8337500095367432
