accuracy: 0.9753000140190125
architecture: in1:100|hidden:60|out1:30|out2:10--recur:30
architecture_name: s3_network
batch: 200
column_at_a_time: 4
dims: 28
epoch: 50
experiment_name: rnn-2017-10-18--21-54
lr: 0.005
max_seq_length: 28
seq_length: 7
