accuracy: 0.9585999846458435
architecture: in1:512|hidden:256|out1:128|out2:10--recur:256
architecture_name: s3_network
batch: 50
column_at_a_time: 28
dataset: mnist
dims: 28
epoch: 50
experiment_name: s3-mnist-seq-1---2017-12-13--13-02-51
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 1
val_accuracy: 0.9574166536331177
