accuracy: 0.8837000131607056
architecture: hidden:512||out:10--recur:256
architecture_name: s2_network
batch: 50
column_at_a_time: 28
dataset: fashion-mnist
dims: 28
epoch: 50
experiment_name: s2-fashion-mnist-seq-1---2017-12-13--21-22-01
keep_prob: 0.5
lr: 0.0005
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 1
val_accuracy: 0.8961666822433472
