accuracy: 0.9785000085830688
architecture: in1:512|hidden:128|out1:64|out2:10--recur:256
architecture_name: s3_network
batch: 50
column_at_a_time: 7
dataset: mnist
dims: 28
epoch: 50
experiment_name: s3-mnist-seq-4---2017-12-13--13-36-56
keep_prob: 0.5
lr: 0.0005
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 4
val_accuracy: 0.9756666421890259
