accuracy: 0.7425000071525574
architecture: in1:250|hidden:500|out1:250|out2:10--recur:250
architecture_name: s3_network
batch: 50
column_at_a_time: 28
dataset: fashion-mnist
dims: 28
epoch: 5
experiment_name: s3-fashion-mnist-seq-1---2017-12-10--21-49-07
keep_prob: 0.5
lr: 5.0e-05
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 1
val_accuracy: 0.7570833563804626
