accuracy: 0.9926000237464905
architecture: conv1:5x5x24=>2x2[2,2]|conv2:3x3x32=>2x2[2,2]|in1:128|recur:96|out2:10
architecture_name: convrlstm
batch: 50
column_at_a_time: 7
dataset: mnist-3-digits-maj
dims: 28
epoch: 100
experiment_name: convrlstm-mnist-3-digits-maj-seq-12---2018-04-07--02-50-56
keep_prob: 0.8
lr: 0.0002
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.9895833134651184
