parameters:
  hidden_units: [500]
  recurrent_units: [250]
  in1_units: [250]
  out1_units: [250]
  keep_prob: [0.5]
  length: [4, 7, 14]
  lr: [0.00125, 0.005]

command: |
  python scripts/train.py s3_network \
    --seq-length {length} \
    --epoch 100 \
    --lr {lr} \
    --batch 50 \
    --architecture-str 'in1:{in1_units}|hidden:{hidden_units}|out1:{out1_units}|out2:10--recur:{recurrent_units}' \
    --keep_prob {keep_prob} --verbose --output_dir ./experiment-results/sprint-8-no-dropout-rr
