accuracy: 0.8439000248908997
architecture: in1:512|in2:256|hidden:128|out1:64|out2:10--recur:128
architecture_name: deep_4l_network
batch: 50
column_at_a_time: 2
dataset: fashion-mnist
dims: 28
epoch: 200
experiment_name: deep_4l_network-fashion-mnist-seq-14---2018-01-17--22-06-27
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 14
val_accuracy: 0.8514166474342346
