accuracy: 0.9086999893188477
architecture: in1:256|hidden:128|out1:32|out2:10--recur:256
architecture_name: deep_do_xh
batch: 50
column_at_a_time: 7
dataset: fashion-mnist-3-items-maj
dims: 28
epoch: 200
experiment_name: deep_do_xh-fashion-mnist-3-items-maj-seq-12---2018-03-19--21-55-45
keep_prob: 0.8
lr: 0.0002
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.9161666631698608
