accuracy: 0.8672000169754028
architecture: hidden:768|out:10--recur:128
architecture_name: s2_network
batch: 50
column_at_a_time: 2
dataset: fashion-mnist
dims: 28
epoch: 200
experiment_name: s2_network-fashion-mnist-seq-14---2017-12-30--14-08-06
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 14
val_accuracy: 0.878166675567627
