accuracy: 0.9117000102996826
architecture: in1:256|recur:72|out2:10
architecture_name: rlstm
batch: 50
column_at_a_time: 7
dataset: fashion-mnist-3-items-maj
dims: 28
epoch: 200
experiment_name: rlstm-fashion-mnist-3-items-maj-seq-12---2018-03-16--22-14-37
keep_prob: 0.8
lr: 0.0002
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.9200833439826965
