accuracy: 0.9075000286102295
architecture: in1:300|hidden:100|out1:50|out2:10--recur:1
architecture_name: s3_network
batch: 50
column_at_a_time: 14
dims: 28
epoch: 100
experiment_name: rnn-2017-11-01--22-29
keep_prob: 0.1
lr: 0.0002
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 2
