accuracy: 0.9656000137329102
architecture: in1:512|hidden:256|out1:64|out2:10--recur:128
architecture_name: s3_network
batch: 50
column_at_a_time: 7
dataset: mnist-3-digits-maj
dims: 28
epoch: 200
experiment_name: s3_network-mnist-3-digits-maj-seq-12---2018-02-14--21-46-01
keep_prob: 0.5
lr: 0.00025
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.9619166851043701
