accuracy: 0.9921000003814697
architecture: conv1:5x5x24=>2x2[2,2]|conv2:3x3x32=>2x2[2,2]|hidden:128|recur:96|out1:50|out2:10
architecture_name: lenet
batch: 50
column_at_a_time: 28
dataset: mnist
dims: 28
epoch: 100
experiment_name: lenet-mnist-seq-1---2018-03-25--23-07-27
keep_prob: 0.8
lr: 0.0002
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 1
val_accuracy: 0.9904999732971191
