accuracy: 0.917900025844574
architecture: in1:256|hidden:128|out1:32|out2:10--recur:256
architecture_name: deep
batch: 50
column_at_a_time: 7
dataset: fashion-mnist-3-items-maj
dims: 28
epoch: 100
experiment_name: deep-fashion-mnist-3-items-maj-seq-12---2018-03-25--20-12-17--fold-1
keep_prob: 0.8
lr: 0.0002
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.917900025844574
