accuracy: 0.8913999795913696
architecture: in1:256|hidden:128|out1:32|out2:10--recur:256
architecture_name: deep
batch: 50
column_at_a_time: 28
dataset: fashion-mnist
dims: 28
epoch: 100
experiment_name: deep-fashion-mnist-seq-1---2018-03-02--22-18-07
keep_prob: 0.8
lr: 0.0002
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 1
val_accuracy: 0.9016666412353516
