accuracy: 0.9740999937057495
architecture: hidden:256|out:10--recur:64
architecture_name: s2_network
batch: 50
column_at_a_time: 4
dataset: mnist
dims: 28
epoch: 50
experiment_name: s2-seq-7---2017-12-13--12-03-43
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 7
val_accuracy: 0.9728333353996277
