accuracy: 0.9800999760627747
architecture: hidden:256|out:10--recur:256
architecture_name: s2_network
batch: 50
column_at_a_time: 28
dataset: mnist
dims: 28
epoch: 200
experiment_name: s2_network-mnist-seq-1---2018-02-24--10-32-53
keep_prob: 0.8
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 1
val_accuracy: 0.9799166917800903
