accuracy: 0.9803000092506409
architecture: hidden:768|out:10--recur:1
architecture_name: s2_network
batch: 50
column_at_a_time: 28
dataset: mnist
dims: 28
epoch: 200
experiment_name: s2_network-mnist-seq-1---2018-01-29--00-37-19
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 1
val_accuracy: 0.9793333411216736
