accuracy: 0.9807000160217285
architecture: hidden:768|out:10--recur:0
architecture_name: s2_network
batch: 50
column_at_a_time: 28
dataset: mnist
dims: 28
epoch: 200
experiment_name: s2_network-mnist-seq-1---2017-12-31--08-06-52
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 1
val_accuracy: 0.9800000190734863
