accuracy: 0.8544999957084656
architecture: hidden:512||out:10--recur:256
architecture_name: s2_network
batch: 50
column_at_a_time: 2
dataset: fashion-mnist
dims: 28
epoch: 50
experiment_name: s2-fashion-mnist-seq-14---2017-12-13--20-52-06
keep_prob: 0.5
lr: 0.0005
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 14
val_accuracy: 0.8678333163261414
