accuracy: 0.9857000112533569
architecture: in1:256|recur:72|out2:10
architecture_name: rlstm_persisted_dropout
batch: 50
column_at_a_time: 7
dataset: mnist-3-digits-maj
dims: 28
epoch: 100
experiment_name: rlstm_persisted_dropout-mnist-3-digits-maj-seq-12---2018-03-24--22-14-15
keep_prob: 0.8
lr: 0.0002
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.9808333516120911
