accuracy: 0.9550999999046326
architecture: in1:200|hidden:100|out1:50|out2:10--recur:10
architecture_name: s3_network
batch: 50
column_at_a_time: 14
dims: 28
epoch: 100
experiment_name: s3-seq-2---2017-11-05--16-17
keep_prob: 0.1
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 2
