accuracy: 0.3749000132083893
architecture: hidden:100|out:10--recur:7
architecture_name: s2_network
batch: 200
column_at_a_time: 4
dims: 28
epoch: 50
experiment_name: rnn-2017-10-19--12-23
keep_prob: 0.8
lr: 0.005
max_seq_length: 28
seq_length: 7
