accuracy: 0.8288999795913696
architecture: in1:50|hidden:100|out1:75|out2:10--recur:100
architecture_name: s3_network
batch: 100
column_at_a_time: 2
dims: 28
epoch: 50
experiment_name: rnn-2017-10-19--19-43
keep_prob: 0.8
lr: 0.0025
max_seq_length: 28
seq_length: 14
