accuracy: 0.9857000112533569
architecture: in1:512|hidden:256|out1:64|out2:10--recur:128
architecture_name: deep
batch: 50
column_at_a_time: 7
dataset: mnist-3-digits
dims: 28
epoch: 200
experiment_name: deep-mnist-3-digits-seq-12---2018-02-26--17-23-27
keep_prob: 0.8
lr: 0.00025
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.9849166870117188
