accuracy: 0.809499979019165
architecture: in1:60|hidden:30|out1:20|out2:10--recur:100
architecture_name: s3_network
batch: 50
column_at_a_time: 7
dims: 28
epoch: 200
experiment_name: rnn-2017-11-03--13-17
keep_prob: 0.05
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 4
