accuracy: 0.9194999933242798
architecture: conv1:5x5x24=>2x2[2,2]|conv2:3x3x48=>2x2[2,2]|hidden:256|out1:128|out2:10--recur:128
architecture_name: convdeep_4l_network
batch: 50
column_at_a_time: 7
dataset: fashion-mnist
dims: 28
epoch: 200
experiment_name: convdeep_4l_network-fashion-mnist-seq-4---2018-01-31--10-02-25
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 4
val_accuracy: 0.9268333315849304
