accuracy: 0.9039000272750854
architecture: conv1:5x5x16=>2x2[2,2]|conv2:5x5x32=>2x2[2,2]|hidden:512|out1:256|out2:10--recur:256
architecture_name: convdeep_4l_network
batch: 50
column_at_a_time: 7
dataset: fashion-mnist
dims: 28
epoch: 100
experiment_name: convdeep_4l_network-fashion-mnist-seq-4---2017-12-21--17-14-15
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 4
val_accuracy: 0.9132500290870667
