accuracy: 0.9800999760627747
architecture: in1:512|in2:256|hidden:128|out1:64|out2:10--recur:128
architecture_name: deep_4l_network
batch: 50
column_at_a_time: 7
dataset: mnist
dims: 28
epoch: 200
experiment_name: deep_4l_network-mnist-seq-4---2017-12-30--19-02-34
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 4
val_accuracy: 0.9777500033378601
