accuracy: 0.9824000000953674
architecture: hidden:500|out:10--recur:250
architecture_name: s2_network
batch: 50
column_at_a_time: 4
dims: 28
epoch: 50
experiment_name: s2-seq-7---2017-12-07--22-21-42
keep_prob: 0.8
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 7
val_accuracy: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - f4
  - 0
  - 1
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  MzN7Pw==
