accuracy: 0.8378999829292297
architecture: in1:250|hidden:500|out1:250|out2:10--recur:250
architecture_name: s3_network
batch: 50
column_at_a_time: 28
dataset: fashion-mnist
dims: 28
epoch: 50
experiment_name: s3-fashion-mnist-seq-1---2017-12-10--14-07-09
keep_prob: 0.5
lr: 0.0005
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 1
val_accuracy: 0.8512499928474426
