accuracy: 0.7854999899864197
architecture: hidden:300|out:10--recur:100
architecture_name: s2_network
batch: 50
column_at_a_time: 28
dims: 28
epoch: 50
experiment_name: rnn-2017-10-31--21-37
keep_prob: 0.01
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 1
