accuracy: 0.8980000019073486
architecture: in1:100|hidden:30|out1:20|out2:10--recur:5
architecture_name: s3_network
batch: 50
column_at_a_time: 14
dims: 28
epoch: 500
experiment_name: rnn-2017-11-02--22-11
keep_prob: 0.1
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 2
