accuracy: 0.6538000106811523
architecture: in1:100|hidden:30|out1:20|out2:10--recur:20
architecture_name: s3_network
batch: 50
column_at_a_time: 7
dims: 28
epoch: 500
experiment_name: rnn-2017-11-03--01-20
keep_prob: 0.01
lr: 0.00025
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 4
