accuracy: 0.5881999731063843
architecture: hidden:400|out:10--recur:100
architecture_name: s2_network
batch: 100
column_at_a_time: 4
dims: 28
epoch: 50
experiment_name: rnn-2017-10-24--23-07
keep_prob: 1
lr: 0.001
max_seq_length: 28
seq_length: 7
