accuracy: 0.5339000225067139
architecture: in1:300|hidden:100|out1:50|out2:10--recur:50
architecture_name: s3_network
batch: 50
column_at_a_time: 28
dims: 28
epoch: 50
experiment_name: rnn-2017-10-31--19-43
keep_prob: 0.01
lr: 0.0005
max_seq_length: 28
seq_length: 1
