accuracy: 0.9805999994277954
architecture: in1:400|hidden:400|out1:200|out2:10--recur:100
architecture_name: s3_network
batch: 100
column_at_a_time: 1
dims: 28
epoch: 50
experiment_name: rnn-2017-11-01--07-18
keep_prob: 0.2
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 28
