accuracy: 0.8529000282287598
architecture: in1:500|hidden:1000|out1:500|out2:10--recur:375
architecture_name: s3_network
batch: 50
column_at_a_time: 28
dataset: fashion-mnist
dims: 28
epoch: 50
experiment_name: s3-fashion-mnist-seq-1---2017-12-10--21-04-16
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 1
val_accuracy: 0.8620833158493042
