accuracy: 0.9811999797821045
architecture: hidden:768|out:10--recur:128
architecture_name: s2_network
batch: 50
column_at_a_time: 7
dataset: mnist-3-digits
dims: 28
epoch: 200
experiment_name: s2_network-mnist-3-digits-seq-12---2018-02-07--11-14-03
keep_prob: 0.5
lr: 0.0001
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.9795833230018616
