accuracy: 0.9868000149726868
architecture: in1:256|hidden:128|out1:32|out2:10--recur:256
architecture_name: deep
batch: 50
column_at_a_time: 4
dataset: mnist
dims: 28
epoch: 100
experiment_name: deep-mnist-seq-7---2018-03-01--17-57-17
keep_prob: 0.8
lr: 0.0002
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 7
val_accuracy: 0.9852499961853027
