accuracy: 0.8343999981880188
architecture: in1:256|hidden:128|out1:64|out2:10--recur:250
architecture_name: s3_network
batch: 32
column_at_a_time: 28
dataset: fashion-mnist
dims: 28
epoch: 50
experiment_name: s3-fashion-mnist-seq-1---2017-12-11--23-43-52
keep_prob: 0.8
lr: 0.0005
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 1
val_accuracy: 0.8543333411216736
