accuracy: 0.8848000168800354
architecture: in1:128|in2:256|hidden:128|out1:32|out2:10--recur:256
architecture_name: deep_v2
batch: 50
column_at_a_time: 28
dataset: fashion-mnist
dims: 28
epoch: 100
experiment_name: deep_v2-fashion-mnist-seq-1---2018-03-02--23-01-21
keep_prob: 0.8
lr: 0.0002
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 1
val_accuracy: 0.8966666460037231
