accuracy: 0.9359999895095825
architecture: in1:400|hidden:30|out1:20|out2:10--recur:5
architecture_name: s3_network
batch: 50
column_at_a_time: 14
dims: 28
epoch: 100
experiment_name: rnn-2017-11-02--22-49
keep_prob: 0.05
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 2
