accuracy: 0.9825000166893005
architecture: in1:480|in2:192|hidden:256|out1:64|out2:10--recur:128
architecture_name: deep_4l_network
batch: 50
column_at_a_time: 7
dataset: mnist-3-digits-maj
dims: 28
epoch: 200
experiment_name: deep_4l_network-mnist-3-digits-maj-seq-12---2018-02-16--22-51-21
keep_prob: 0.8
lr: 0.00025
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.9831666946411133
