accuracy: 0.883400022983551
architecture: in1:256|hidden:128|out1:64|out2:10--recur:250
architecture_name: s3_network
batch: 50
column_at_a_time: 28
dataset: fashion-mnist
dims: 28
epoch: 100
experiment_name: s3-fashion-mnist-seq-1---2017-12-11--23-18-36
keep_prob: 0.8
lr: 0.001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 1
val_accuracy: 0.8970000147819519
