accuracy: 0.8888999819755554
architecture: in1:128|in2:256|hidden:128|out1:32|out2:10--recur:256
architecture_name: deep_v2
batch: 50
column_at_a_time: 4
dataset: fashion-mnist
dims: 28
epoch: 100
experiment_name: deep_v2-fashion-mnist-seq-7---2018-03-02--22-26-30
keep_prob: 0.8
lr: 0.0002
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 7
val_accuracy: 0.8949999809265137
