accuracy: 0.9585000276565552
architecture: in1:100|hidden:75|out1:25|out2:10--recur:10
architecture_name: s3_network
batch: 50
column_at_a_time: 14
dims: 28
epoch: 200
experiment_name: rnn-2017-11-02--00-42
keep_prob: 0.2
lr: 5.0e-05
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 2
