accuracy: 0.09799999743700027
architecture: hidden:50|out:10--recur:100
architecture_name: s2_network
batch: 100
column_at_a_time: 1
dims: 28
epoch: 50
experiment_name: rnn-2017-10-19--21-52
keep_prob: 0.8
lr: 0.0025
max_seq_length: 28
seq_length: 28
