accuracy: 0.5841000080108643
architecture: hidden:150|out:10--recur:7
architecture_name: s2_network
batch: 100
column_at_a_time: 4
epoch: 50
experiment_name: rnn-2017-10-16--10-10
lr: 0.005
seq_length: 7
