accuracy: 0.7829999923706055
architecture: hidden:500|out:10--recur:250
architecture_name: s2_network
batch: 50
column_at_a_time: 7
dims: 28
epoch: 100
experiment_name: s2-seq-4---2017-12-08--10-43-27
keep_prob: 1
lr: 0.001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 4
val_accuracy: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - f4
  - 0
  - 1
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  JnhIPw==
