accuracy: 0.8679999709129333
architecture: in1:256|hidden:128|out1:64|out2:10--recur:32
architecture_name: s3_network
batch: 32
column_at_a_time: 7
dataset: fashion-mnist
dims: 28
epoch: 50
experiment_name: s3-fashion-mnist-seq-4---2017-12-12--00-20-26
keep_prob: 0.8
lr: 0.0005
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 4
val_accuracy: 0.8795833587646484
