accuracy: 0.9585000276565552
architecture: in1:300|hidden:100|out1:50|out2:10--recur:5
architecture_name: s3_network
batch: 50
column_at_a_time: 14
dims: 28
epoch: 100
experiment_name: rnn-2017-11-01--22-12
keep_prob: 0.1
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 2
