accuracy: 0.8050000071525574
architecture: in1:100|hidden:60|out1:30|out2:10--recur:30
architecture_name: s3_network
batch: 200
column_at_a_time: 1
dims: 28
epoch: 30
experiment_name: rnn-2017-10-18--22-25
lr: 0.005
max_seq_length: 28
seq_length: 28
