accuracy: 0.9138000011444092
architecture: conv1:5x5x48=>2x2[2,2]|conv2:3x3x56=>2x2[2,2]|hidden:256|out1:64|out2:10--recur:128
architecture_name: convdeep_4l_network
batch: 50
column_at_a_time: 7
dataset: fashion-mnist-3-items
dims: 28
epoch: 200
experiment_name: convdeep_4l_network-fashion-mnist-3-items-seq-12---2018-02-16--23-15-48
keep_prob: 0.8
lr: 0.0001
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.9225000143051147
