accuracy: 0.9794999957084656
architecture: hidden:768|out:10--recur:128
architecture_name: s2_network
batch: 50
column_at_a_time: 2
dataset: mnist
dims: 28
epoch: 200
experiment_name: s2_network-mnist-seq-14---2017-12-30--13-01-05
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 14
val_accuracy: 0.9785833358764648
