accuracy: 0.9768000245094299
architecture: conv1:5x5x24=>2x2[2,2]|conv2:3x3x32=>2x2[2,2]|in1:128|hidden:128|out1:32|out2:10--recur:256
architecture_name: convdeep_transcribe
batch: 50
column_at_a_time: 7
dataset: mnist-3-digits-maj
dims: 28
epoch: 100
experiment_name: convdeep_transcribe-mnist-3-digits-maj-seq-12---2018-03-26--00-05-20--fold-2
keep_prob: 0.8
lr: 0.0002
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.9768000245094299
