accuracy: 0.9771000146865845
architecture: in1:512|hidden:128|out1:64|out2:10--recur:256
architecture_name: s3_network
batch: 50
column_at_a_time: 4
dataset: mnist
dims: 28
epoch: 50
experiment_name: s3-mnist-seq-7---2017-12-13--13-46-22
keep_prob: 0.5
lr: 0.0005
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 7
val_accuracy: 0.9746666550636292
