accuracy: 0.5042999982833862
architecture: hidden:100|out:10--recur:50
architecture_name: s2_network
batch: 100
column_at_a_time: 4
dims: 28
epoch: 50
experiment_name: rnn-2017-10-19--19-25
keep_prob: 0.8
lr: 0.0025
max_seq_length: 28
seq_length: 7
