accuracy: 0.8912000060081482
architecture: in1:512|in2:256|hidden:128|out1:64|out2:10--recur:1
architecture_name: deep_4l_network
batch: 50
column_at_a_time: 28
dataset: fashion-mnist
dims: 28
epoch: 200
experiment_name: deep_4l_network-fashion-mnist-seq-1---2017-12-31--14-48-44
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 1
val_accuracy: 0.9022499918937683
