accuracy: 0.9797999858856201
architecture: in1:512|in2:256|hidden:128|out1:64|out2:10--recur:128
architecture_name: deep_4l_network
batch: 50
column_at_a_time: 4
dataset: mnist
dims: 28
epoch: 200
experiment_name: deep_4l_network-mnist-seq-7---2018-01-28--19-31-55
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 7
val_accuracy: 0.9770833253860474
