accuracy: 0.460099995136261
architecture_name: s3_network
column_at_a_time: 1
epoch: 10
experiment_name: rnn-2017-10-11--17-13
layer_hidden: 60
layer_in1: 10
layer_out1: 30
layer_out2: 10
layer_recur: 20
lr: 0.005
seq_length: 28
