accuracy: 0.9963014721870422
architecture: conv1:5x5x24=>2x2[2,2]|conv2:3x3x32=>2x2[2,2]|in1:128|recur:96|out2:10
architecture_name: convrlstm_persisted_dropout
batch: 50
column_at_a_time: 7
dataset: mnist-3-digits-maj
dims: 28
epoch: 100
experiment_name: convrlstm_persisted_dropout-mnist-3-digits-maj-seq-12---2018-03-25--14-11-49--fold-0
keep_prob: 0.8
lr: 0.0002
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.9963014721870422
