accuracy: 0.9690999984741211
architecture: in1:100|hidden:75|out1:25|out2:10--recur:1
architecture_name: s3_network
batch: 50
column_at_a_time: 14
dims: 28
epoch: 100
experiment_name: rnn-2017-11-02--00-12
keep_prob: 0.8
lr: 8.0e-05
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 2
