accuracy: 0.9839000105857849
architecture: hidden:256|out:10--recur:256
architecture_name: shallow
batch: 50
column_at_a_time: 7
dataset: mnist-3-digits-maj
dims: 28
epoch: 200
experiment_name: shallow-mnist-3-digits-maj-seq-12---2018-02-27--05-32-59
keep_prob: 0.8
lr: 0.0001
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.9780833125114441
