accuracy: 0.9807000160217285
architecture: hidden:256|out:10--recur:256
architecture_name: s2_network
batch: 50
column_at_a_time: 4
dataset: mnist
dims: 28
epoch: 100
experiment_name: s2-mnist-seq-7---2017-12-13--14-13-10
keep_prob: 0.5
lr: 0.0005
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 7
val_accuracy: 0.9788333177566528
