accuracy: 0.7473000288009644
architecture: in1:300|hidden:100|out1:50|out2:10--recur:50
architecture_name: s3_network
batch: 100
column_at_a_time: 14
dims: 28
epoch: 50
experiment_name: rnn-2017-11-01--21-24
keep_prob: 0.01
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 2
