accuracy: 0.980400025844574
architecture: in1:1000|hidden:300|out1:100|out2:10--recur:50
architecture_name: s3_network
batch: 50
column_at_a_time: 7
dims: 28
epoch: 100
experiment_name: s3-seq-4---2017-11-09--21-29-46
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 4
val_accuracy: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - f4
  - 0
  - 1
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  Sgx6Pw==
