accuracy: 0.9909999966621399
architecture: conv1:5x5x24=>2x2[2,2]|conv2:3x3x48=>2x2[2,2]|hidden:256|out1:128|out2:10--recur:128
architecture_name: convdeep_4l_network
batch: 50
column_at_a_time: 4
dataset: mnist
dims: 28
epoch: 200
experiment_name: convdeep_4l_network-mnist-seq-7---2017-12-31--00-21-41
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 7
val_accuracy: 0.9911666512489319
