accuracy: 0.8950999975204468
architecture: conv1:5x5x24=>2x2[2,2]|conv2:3x3x32=>2x2[2,2]|in1:128|recur:96|out2:10
architecture_name: convtran_rlstm_persisted_dropout
batch: 50
column_at_a_time: 7
dataset: fashion-mnist-3-items-maj
dims: 28
epoch: 100
experiment_name: convtran_rlstm_persisted_dropout-fashion-mnist-3-items-maj-seq-12---2018-03-27--05-10-59--fold-4
keep_prob: 0.8
lr: 0.0002
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.8950999975204468
