accuracy: 0.9797000288963318
architecture: in1:512|in2:256|hidden:128|out1:64|out2:10--recur:128
architecture_name: deep_4l_network
batch: 50
column_at_a_time: 28
dataset: mnist
dims: 28
epoch: 100
experiment_name: deep_4l_network-mnist-seq-1---2017-12-30--01-40-43
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 1
val_accuracy: 0.9758333563804626
