accuracy: 0.8621000051498413
architecture: in1:1024|hidden:512|out1:256|out2:10--recur:256
architecture_name: s3_network
batch: 50
column_at_a_time: 28
dataset: fashion-mnist
dims: 28
epoch: 50
experiment_name: s3-fashion-mnist-seq-1---2017-12-14--00-28-09
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 1
val_accuracy: 0.874750018119812
