accuracy: 0.8255000114440918
architecture: in1:300|hidden:100|out1:50|out2:10--recur:50
architecture_name: s3_network
batch: 50
column_at_a_time: 28
dims: 28
epoch: 1
experiment_name: s3-seq-1---2017-11-04--16-41
keep_prob: 0.2
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 1
