accuracy: 0.923799991607666
architecture: in1:128|in2:256|hidden:128|out1:32|out2:10--recur:256
architecture_name: deep_v2
batch: 50
column_at_a_time: 7
dataset: fashion-mnist-3-items-maj
dims: 28
epoch: 100
experiment_name: deep_v2-fashion-mnist-3-items-maj-seq-12---2018-03-25--19-36-54--fold-1
keep_prob: 0.8
lr: 0.0002
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.923799991607666
