accuracy: 0.8169999718666077
architecture: in1:512|in2:256|hidden:128|out1:64|out2:10--recur:128
architecture_name: deep_4l_network
batch: 50
column_at_a_time: 7
dataset: fashion-mnist-3-items
dims: 28
epoch: 200
experiment_name: deep_4l_network-fashion-mnist-3-items-seq-12---2018-02-08--08-47-11
keep_prob: 0.5
lr: 0.0001
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.8261666893959045
