accuracy: 0.8756999969482422
architecture: hidden:768|out:10--recur:128
architecture_name: s2_network
batch: 50
column_at_a_time: 7
dataset: fashion-mnist-3-items-maj
dims: 28
epoch: 200
experiment_name: s2_network-fashion-mnist-3-items-maj-seq-12---2018-02-14--21-50-24
keep_prob: 0.5
lr: 0.0001
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.887333333492279
