accuracy: 0.9811000227928162
architecture: hidden:256|out:10--recur:256
architecture_name: shallow
batch: 50
column_at_a_time: 28
dataset: mnist
dims: 28
epoch: 100
experiment_name: shallow-mnist-seq-1---2018-03-01--16-26-38
keep_prob: 0.8
lr: 0.0002
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 1
val_accuracy: 0.9803333282470703
