accuracy: 0.9815000295639038
architecture: in1:800|hidden:100|out1:70|out2:10--recur:50
architecture_name: s3_network
batch: 50
column_at_a_time: 4
dims: 28
epoch: 100
experiment_name: s3-seq-7---2017-11-05--23-00-40
keep_prob: 0.2
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 7
val_accuracy: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - f4
  - 0
  - 1
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  qX97Pw==
