accuracy: 0.8379999995231628
architecture: in1:250|hidden:500|out1:250|out2:10--recur:250
architecture_name: s3_network
batch: 50
column_at_a_time: 7
dataset: fashion-mnist
dims: 28
epoch: 50
experiment_name: s3-fashion-mnist-seq-4---2017-12-10--13-31-38
keep_prob: 0.5
lr: 0.0002
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 4
val_accuracy: 0.8485833406448364
