accuracy: 0.9833999872207642
architecture: in1:800|hidden:400|out1:400|out2:10--recur:100
architecture_name: s3_network
batch: 100
column_at_a_time: 4
dims: 28
epoch: 50
experiment_name: rnn-2017-10-22--03-20
keep_prob: 1
lr: 0.001
max_seq_length: 28
seq_length: 7
