accuracy: 0.5403000116348267
architecture: in1:400|hidden:400|out1:200|out2:10--recur:100
architecture_name: s3_network
batch: 50
column_at_a_time: 4
dims: 28
epoch: 50
experiment_name: rnn-2017-10-31--22-59
keep_prob: 0.1
lr: 0.001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 7
