accuracy: 0.6218000054359436
architecture: in1:500|hidden:300|out1:200|out2:10--recur:50
architecture_name: s3_network
batch: 50
column_at_a_time: 2
dims: 28
epoch: 50
experiment_name: s3-seq-14---2017-11-12--14-26-59
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 14
val_accuracy: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - f4
  - 0
  - 1
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  oYwePw==
