accuracy: 0.972100019454956
architecture: in1:100|hidden:100|out1:75|out2:10--recur:50
architecture_name: s3_network
batch: 100
column_at_a_time: 4
dims: 28
epoch: 50
experiment_name: rnn-2017-10-19--15-28
keep_prob: 1
lr: 0.005
max_seq_length: 28
seq_length: 7
