accuracy: 0.8942999839782715
architecture: in1:256|hidden:128|out1:32|out2:10--recur:256
architecture_name: deep
batch: 50
column_at_a_time: 7
dataset: fashion-mnist
dims: 28
epoch: 100
experiment_name: deep-fashion-mnist-seq-4---2018-03-02--22-05-47
keep_prob: 0.8
lr: 0.0002
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 4
val_accuracy: 0.9028333425521851
