accuracy: 0.5321999788284302
architecture_name: s3_network
column_at_a_time: 1
epoch: 20
experiment_name: rnn-2017-10-11--16-38
layer_hidden: 60
layer_in1: 20
layer_out1: 30
layer_out2: 10
layer_recur: 40
lr: 0.005
seq_length: 28
