accuracy: 0.34200000762939453
architecture_name: s3_network
column_at_a_time: 1
epoch: 20
experiment_name: rnn-2017-10-11--17-52
layer_hidden: 60
layer_in1: 10
layer_out1: 30
layer_out2: 10
layer_recur: 40
lr: 0.01
seq_length: 28
