accuracy: 0.7204999923706055
architecture_name: s3_network
column_at_a_time: 1
epoch: 50
experiment_name: rnn-2017-10-11--17-43
layer_hidden: 60
layer_in1: 10
layer_out1: 50
layer_out2: 10
layer_recur: 40
lr: 0.005
seq_length: 28
