accuracy: 0.9882000088691711
architecture: in1:256|hidden:128|out1:32|out2:10--recur:256
architecture_name: s3_network
batch: 50
column_at_a_time: 4
dataset: mnist
dims: 28
epoch: 200
experiment_name: s3_network-mnist-seq-7---2018-02-24--14-46-26
keep_prob: 0.8
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 7
val_accuracy: 0.9861666560173035
