accuracy: 0.9814000129699707
architecture: in1:512|hidden:128|out1:64|out2:10--recur:256
architecture_name: s3_network
batch: 50
column_at_a_time: 4
dataset: mnist
dims: 28
epoch: 100
experiment_name: s3-mnist-seq-7---2017-12-13--17-23-19
keep_prob: 0.5
lr: 0.0005
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 7
val_accuracy: 0.9793333411216736
