accuracy: 0.9315999746322632
architecture: in1:100|hidden:50|out1:50|out2:10--recur:50
architecture_name: s3_network
batch: 100
column_at_a_time: 4
dims: 28
epoch: 80
experiment_name: rnn-2017-10-23--00-03
keep_prob: 0.5
lr: 0.001
max_seq_length: 28
seq_length: 7
