accuracy: 0.9096999764442444
architecture: in1:200|hidden:30|out1:20|out2:10--recur:5
architecture_name: s3_network
batch: 50
column_at_a_time: 7
dims: 28
epoch: 50
experiment_name: rnn-2017-11-03--16-06
keep_prob: 0.1
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 4
