accuracy: 0.9829999804496765
architecture: in1:512|in2:265|hidden:128|out1:64|out2:10--recur:128
architecture_name: deep_4l_network
batch: 50
column_at_a_time: 28
dataset: mnist-7-digits
dims: 28
epoch: 200
experiment_name: deep_4l_network-mnist-7-digits-seq-7---2018-02-19--21-52-54
keep_prob: 0.8
lr: 0.00025
max_seq_length: 196
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 7
val_accuracy: 0.981166660785675
