accuracy: 0.9815999865531921
architecture: hidden:1000|out:10--recur:100
architecture_name: s2_network
batch: 100
column_at_a_time: 4
dims: 28
epoch: 50
experiment_name: rnn-2017-10-25--03-06
keep_prob: 1
lr: 0.001
max_seq_length: 28
seq_length: 7
