accuracy: 0.8974000215530396
architecture: hidden:256|out:10--recur:256
architecture_name: s2_network
batch: 50
column_at_a_time: 7
dataset: fashion-mnist
dims: 28
epoch: 200
experiment_name: s2_network-fashion-mnist-seq-4---2018-02-24--13-34-14
keep_prob: 0.8
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 4
val_accuracy: 0.9005833268165588
