accuracy: 0.7669000029563904
architecture: hidden:500|out:10--recur:100
architecture_name: s2_network
batch: 50
column_at_a_time: 28
dims: 28
epoch: 100
experiment_name: rnn-2017-10-31--20-47
keep_prob: 0.8
lr: 0.0005
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 1
