accuracy: 0.9814000129699707
architecture: in1:1000|hidden:200|out1:200|out2:10--recur:50
architecture_name: s3_network
batch: 100
column_at_a_time: 4
dims: 28
epoch: 50
experiment_name: rnn-2017-10-21--21-00
keep_prob: 0.5
lr: 0.001
max_seq_length: 28
seq_length: 7
