accuracy: 0.8924000263214111
architecture: in1:512|hidden:256|out1:64|out2:10--recur:0
architecture_name: s3_network
batch: 50
column_at_a_time: 28
dataset: fashion-mnist
dims: 28
epoch: 200
experiment_name: s3_network-fashion-mnist-seq-1---2017-12-31--09-01-48
keep_prob: 0.5
lr: 0.0002
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 1
val_accuracy: 0.9016666412353516
