accuracy: 0.972100019454956
architecture: in1:120|hidden:40|out1:30|out2:10--recur:50
architecture_name: s3_network
batch: 100
column_at_a_time: 4
dims: 28
epoch: 80
experiment_name: rnn-2017-10-23--07-11
keep_prob: 1
lr: 0.001
max_seq_length: 28
seq_length: 7
