accuracy: 0.977400004863739
architecture: hidden:800|out:10--recur:200
architecture_name: s2_network
batch: 50
column_at_a_time: 2
dims: 28
epoch: 100
experiment_name: s2-seq-14---2017-11-08--08-25-42
keep_prob: 0.2
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 14
val_accuracy: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - f4
  - 0
  - 1
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  b8t6Pw==
