accuracy: 0.9861000180244446
architecture: in1:512|hidden:256|out1:64|out2:10--recur:128
architecture_name: s3_network
batch: 50
column_at_a_time: 7
dataset: mnist
dims: 28
epoch: 200
experiment_name: s3_network-mnist-seq-4---2017-12-30--14-46-26
keep_prob: 0.5
lr: 0.0002
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 4
val_accuracy: 0.984749972820282
