accuracy: 0.9825999736785889
architecture: in1:512|hidden:128|out1:64|out2:10--recur:256
architecture_name: s3_network
batch: 50
column_at_a_time: 7
dataset: mnist
dims: 28
epoch: 100
experiment_name: s3-mnist-seq-4---2017-12-13--14-28-48
keep_prob: 0.5
lr: 0.0005
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 4
val_accuracy: 0.9796666502952576
