accuracy: 0.9161999821662903
architecture: in1:200|hidden:100|out1:50|out2:10--recur:10
architecture_name: s3_network
batch: 50
column_at_a_time: 14
dims: 28
epoch: 100
experiment_name: s3-seq-2---2017-11-05--19-17
keep_prob: 0.1
lr: 1.0e-05
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 2
