accuracy: 0.8738999962806702
architecture: hidden:768|out:10--recur:128
architecture_name: s2_network
batch: 50
column_at_a_time: 4
dataset: fashion-mnist
dims: 28
epoch: 200
experiment_name: s2_network-fashion-mnist-seq-7---2017-12-30--13-47-58
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 7
val_accuracy: 0.8815000057220459
