accuracy: 0.9822999835014343
architecture: hidden:500|out:10--recur:250
architecture_name: s2_network
batch: 50
column_at_a_time: 7
dataset: mnist
dims: 28
epoch: 100
experiment_name: s2-seq-4---2017-12-13--11-07-37
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 4
val_accuracy: 0.981333315372467
