accuracy: 0.8974000215530396
architecture: in1:256|hidden:128|out1:32|out2:10--recur:256
architecture_name: s3_network
batch: 50
column_at_a_time: 7
dataset: fashion-mnist
dims: 28
epoch: 200
experiment_name: s3_network-fashion-mnist-seq-4---2018-02-24--13-34-15
keep_prob: 0.8
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 4
val_accuracy: 0.9069166779518127
