accuracy: 0.9847984910011292
architecture: conv1:5x5x24=>2x2[2,2]|conv2:3x3x32=>2x2[2,2]|in1:128|recur:96|out2:10
architecture_name: convtran_rlstm_persisted_dropout
batch: 50
column_at_a_time: 7
dataset: mnist-3-digits-maj
dims: 28
epoch: 100
experiment_name: convtran_rlstm_persisted_dropout-mnist-3-digits-maj-seq-12---2018-03-26--19-17-39--fold-5
keep_prob: 0.8
lr: 0.0002
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.9847984910011292
