accuracy: 0.9818999767303467
architecture: in1:300|hidden:100|out1:30|out2:10--recur:50
architecture_name: s3_network
batch: 50
column_at_a_time: 28
dims: 28
epoch: 100
experiment_name: rnn-2017-10-31--14-54
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
seq_length: 1
