accuracy: 0.957099974155426
architecture: in1:50|hidden:200|out1:100|out2:10--recur:10
architecture_name: s3_network
batch: 100
column_at_a_time: 1
dims: 28
epoch: 50
experiment_name: rnn-2017-10-19--23-29
keep_prob: 1
lr: 0.001
max_seq_length: 28
seq_length: 28
