accuracy: 0.09799999743700027
architecture: in1:50|hidden:100|out1:75|out2:10--recur:50
architecture_name: s3_network
batch: 100
column_at_a_time: 2
dims: 28
epoch: 50
experiment_name: rnn-2017-10-19--16-52
keep_prob: 0.8
lr: 0.005
max_seq_length: 28
seq_length: 14
