accuracy: 0.38339999318122864
architecture: hidden:50|out:10--recur:50
architecture_name: s2_network
batch: 100
column_at_a_time: 2
dims: 28
epoch: 50
experiment_name: rnn-2017-10-19--20-22
keep_prob: 1
lr: 0.0025
max_seq_length: 28
seq_length: 14
