accuracy: 0.43810001015663147
architecture: hidden:100|out:10--recur:7
architecture_name: s2_network
batch: 100
column_at_a_time: 4
dims: 28
epoch: 50
experiment_name: rnn-2017-10-19--12-19
keep_prob: 0.5
lr: 0.005
max_seq_length: 28
seq_length: 7
