accuracy: 0.8848000168800354
architecture: in1:256|hidden:128|out1:32|out2:10--recur:256
architecture_name: deep_with_sparsity
batch: 50
column_at_a_time: 7
dataset: fashion-mnist-3-items-maj
dims: 28
epoch: 200
experiment_name: deep_with_sparsity-fashion-mnist-3-items-maj-seq-12---2018-02-27--00-25-48
keep_prob: 0.8
lr: 0.00025
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.8951666951179504
