accuracy: 0.9787999987602234
architecture: in1:512|hidden:256|out1:64|out2:10--recur:1
architecture_name: s3_network
batch: 50
column_at_a_time: 28
dataset: mnist
dims: 28
epoch: 200
experiment_name: s3_network-mnist-seq-1---2017-12-31--13-46-18
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 1
val_accuracy: 0.9789166450500488
