accuracy: 0.8776000142097473
architecture: hidden:700|out:10--recur:100
architecture_name: s2_network
batch: 128
column_at_a_time: 28
dims: 28
epoch: 50
experiment_name: rnn-2017-10-31--13-44
keep_prob: 0.5
lr: 0.002
max_seq_length: 28
seq_length: 1
