accuracy: 0.8899000287055969
architecture: in1:512|hidden:256|out1:64|out2:10--recur:128
architecture_name: s3_network
batch: 50
column_at_a_time: 7
dataset: fashion-mnist-3-items
dims: 28
epoch: 200
experiment_name: s3_network-fashion-mnist-3-items-seq-12---2018-02-16--22-45-51
keep_prob: 0.8
lr: 0.00025
max_seq_length: 84
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 12
val_accuracy: 0.9004166722297668
