accuracy: 0.8794999718666077
architecture: in1:512|hidden:256|out1:64|out2:10--recur:128
architecture_name: s3_network
batch: 50
column_at_a_time: 4
dataset: fashion-mnist
dims: 28
epoch: 200
experiment_name: s3_network-fashion-mnist-seq-7---2017-12-30--17-02-40
keep_prob: 0.5
lr: 0.0002
max_seq_length: 28
optimizer: AdamOptimizer
regularizer: 0.0
seq_length: 7
val_accuracy: 0.8881666660308838
