accuracy: 0.8748000264167786
architecture: hidden:512||out:10--recur:256
architecture_name: s2_network
batch: 50
column_at_a_time: 7
dataset: fashion-mnist
dims: 28
epoch: 50
experiment_name: s2-fashion-mnist-seq-4---2017-12-13--20-26-31
keep_prob: 0.5
lr: 0.0005
max_seq_length: 28
optimizer: AdamOptimizer
seq_length: 4
val_accuracy: 0.8850833177566528
