accuracy: 0.882099986076355
architecture: hidden:700|out:10--recur:100
architecture_name: s2_network
batch: 50
column_at_a_time: 28
dims: 28
epoch: 100
experiment_name: rnn-2017-10-31--14-09
keep_prob: 0.5
lr: 0.0001
max_seq_length: 28
seq_length: 1
